# Bakes the spooky-mode cat (art/cat/cat.html) into assets/cat.png with
# headless Edge, plus a labelled contact sheet at art/cat/sheet.png for review.
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$edge = @("${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe", "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe") |
    Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $edge) { throw 'Microsoft Edge not found' }
$page = 'file:///' + ((Join-Path $PSScriptRoot 'cat\cat.html') -replace '\\', '/') + '#bake'
$profile = Join-Path $env:TEMP 'wanelight-bake'
$dom = & $edge --headless --disable-gpu --user-data-dir="$profile" --dump-dom $page 2>$null | Out-String

function Save-DataUrl($id, $path) {
    if ($dom -notmatch "<pre id=`"$id`"[^>]*>data:image/png;base64,([A-Za-z0-9+/=]+)</pre>") { throw "no $id in page output" }
    [IO.File]::WriteAllBytes($path, [Convert]::FromBase64String($Matches[1]))
    Write-Output ("{0} ({1:N0} bytes)" -f $path, (Get-Item $path).Length)
}
New-Item -ItemType Directory -Force (Join-Path $root 'assets') | Out-Null
Save-DataUrl 'out' (Join-Path $root 'assets\cat.png')
Save-DataUrl 'sheet' (Join-Path $PSScriptRoot 'cat\sheet.png')

# Frame metadata for the agent: clip ranges, and where the mouth and the
# grabbing tentacle's tip are in each frame, so prey lines up with the sprite.
if ($dom -notmatch '<pre id="meta"[^>]*>([^<]+)</pre>') { throw 'no meta in page output' }
$meta = [Net.WebUtility]::HtmlDecode($Matches[1]) | ConvertFrom-Json
$f = [Globalization.CultureInfo]::InvariantCulture
$pt = { param($p) if ($p) { '({0}, {1})' -f ([double]$p[0]).ToString('0.0', $f), ([double]$p[1]).ToString('0.0', $f) } else { '(0.0, 0.0)' } }
$lines = @('//! Generated by art/bake.ps1 from art/cat/cat.html. Do not edit.', '')
$first = 0
foreach ($c in $meta.clips) {
    $lines += "pub const $($c[0].ToUpper()): (usize, usize) = ($first, $($c[1]));"
    $first += [int]$c[1]
}
$n = $meta.frames.Count
$lines += '', '/// Mouth position in each frame (px, facing right).'
$lines += "pub const MOUTH: [(f32, f32); $n] = ["
$lines += ($meta.frames | ForEach-Object { '    ' + (& $pt $_.mouth) + ',' })
$lines += '];', '', '/// Tip of the grabbing tentacle in each frame (px); (0, 0) when the tentacles are in.'
$lines += "pub const TIP: [(f32, f32); $n] = ["
$lines += ($meta.frames | ForEach-Object { '    ' + (& $pt $_.tip) + ',' })
$lines += '];'
$rs = Join-Path $root 'src\agent\cat_frames.rs'
[IO.File]::WriteAllText($rs, ($lines -join "`n") + "`n")
Write-Output "$rs ($n frames)"
